services:
  app:
    image: docuseal-own:latest
    ports:
      - '127.0.0.1:3020:3000'
    volumes:
      - /var/lib/docuseal-own:/data
    restart: unless-stopped
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - APP_URL=${APP_URL}
      - FORCE_SSL=${FORCE_SSL}
